#!/bin/bash

# Go ahead and get sudo powers
sudo -v

# Enable full keyboard access for all controls (e.g. enable Tab in modal dialogs)
defaults write NSGlobalDomain AppleKeyboardUIMode -int 3

# Enable the 2D Dock
defaults write com.apple.dock no-glass -bool true

# Expand save panel by default
defaults write -g NSNavPanelExpandedStateForSaveMode -bool true

# Avoid creating .DS_Store files on network volumes
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true

# Enable Safari’s debug menu
defaults write com.apple.Safari IncludeDebugMenu -bool true

# Show the ~/Library folder
chflags nohidden ~/Library

# Disable save to iCloud default
defaults write NSGlobalDomain NSDocumentSaveNewDocumentsToCloud -bool false

# Disable resume system-wide
defaults write NSGlobalDomain NSQuitAlwaysKeepsWindows -bool false

# Disable auto-correct
defaults write NSGlobalDomain NSAutomaticSpellingCorrectionEnabled -bool false

