export ZSH=$HOME/.oh-my-zsh
export ZSH_THEME="bolted"

plugins=(autojump brew bundler gem git github lighthouse node npm osx rails3 ruby rvm)

source $ZSH/oh-my-zsh.sh

HISTSIZE=5000
HISTFILE=~/.zsh_history
SAVEHIST=5000
setopt    appendhistory
setopt    sharehistory
setopt    incappendhistory

export LC_ALL="C"
export LANG="en_US.UTF-8"

if [ `uname` = "Darwin" ]; then
    alias ls='ls -G'
else
    alias ls='ls --color'
fi

alias ll='ls -lh'
alias la='ls -a'

if [ -f /etc/autojump ]; then
    source /etc/autojump
fi
if [ -d $HOME/.rvm ]; then
    source $HOME/.rvm/scripts/rvm
fi

if [ -f $HOME/.zsh_aliases ]; then
    source $HOME/.zsh_aliases
fi
if [ -f $HOME/.zsh_local ]; then
    source $HOME/.zsh_local
fi
if [ -f $HOME/.aliases ]; then
    source $HOME/.aliases
fi
if [ -f $HOME/.local ]; then
    source $HOME/.local
fi
