export ZSH=$HOME/.oh-my-zsh
export ZSH_THEME=dieter-bright
export DISABLE_AUTO_UPDATE=true
export DISABLE_AUTO_TITLE=true
export LC_ALL="C"
export LANG="en_US.UTF-8"

if [ -f /usr/local/bin/vim ]; then
  export EDITOR="/usr/local/bin/vim"
else
  export EDITOR="/usr/bin/vim"
fi

if [ `uname` = "Darwin" ]; then
    alias ls='ls -G'
else
    alias ls='ls --color'
    alias ai='sudo apt-get install'
    alias as='aptitude search'
    alias au='sudo apt-get update'
    alias ar='sudo apt-add-repository'
fi

alias ll='ls -lh'
alias la='ls -a'
alias tmux="TERM=screen-256color-bce tmux -u"

# Don't correct filenames with these commands
alias cp='nocorrect cp'
alias mkdir='nocorrect mkdir'
alias mv='nocorrect mv'

PATH=""
if [ -d $HOME/Scripts ]; then
    PATH="$HOME/Scripts"
fi
if [ -d $HOME/bin ]; then
    PATH="$HOME/bin"
fi

HISTSIZE=5000
HISTFILE=~/.zsh_history
SAVEHIST=5000
setopt appendhistory
setopt sharehistory
setopt incappendhistory

zstyle ':completion:*:manuals'    separate-sections true
zstyle ':completion:*:manuals.*'  insert-sections   true
zstyle ':completion:*:man:*'      menu yes select

if [ -d $HOME/.rbenv ]; then
    PATH="$PATH:$HOME/.rbenv/shims:$HOME/.rbenv/bin"
    HAS_RBENV=true
fi

SYSTEM_PATH="/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/usr/X11/bin:/bin:/sbin"
[[ $PATH == "" ]] && PATH=$SYSTEM_PATH || PATH="$PATH:$SYSTEM_PATH"
export PATH

[[ ! -z $HAS_RBENV ]] && eval "$(rbenv init -)"

ZSH_CUSTOM=$HOME/.zsh
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern cursor)
plugins=(zsh-syntax-highlighting history-substring-search vi-mode)
source $ZSH/oh-my-zsh.sh

ZSH_HIGHLIGHT_PATTERNS+=('rm -rf *' 'fg=white,bold,bg=red')
ZSH_HIGHLIGHT_PATTERNS+=('sudo ' 'fg=white,bold,bg=red')

bindkey -M vicmd 'k' history-substring-search-up
bindkey -M vicmd 'j' history-substring-search-down
bindkey "^[[A" history-substring-search-up
bindkey "^[[B" history-substring-search-down

if [ -f $HOME/.zsh_aliases ]; then
    source $HOME/.zsh_aliases
fi
if [ -f $HOME/.zsh_local ]; then
    source $HOME/.zsh_local
fi
if [ -f $HOME/.aliases ]; then
    source $HOME/.aliases
fi
if [ -f $HOME/.local ]; then
    source $HOME/.local
fi
if [ -s $HOME/.tmuxifier/init.sh ]; then
  source "$HOME/.tmuxifier/init.sh"
fi

source `brew --prefix`/etc/profile.d/z.sh

